### ISSUE TITLE
K8S plugin goes too deep

### ISSUE THREAD

**Issue by AngeCyp** [alumet-dev/alumet#50]
**Describe the bug**

When Alumet is launch with k8s plugin, crio's layer are reported, I mean, a pod have crio layers, but we don't want to report it, it's unecessary and too deep. We just want pod's global values

**Environment information**
OS: X
Alumet version: 0.6.0
Enabled plugins: K8s, CSV output (CSV one is not relevant)

: please include the commit hash if it's not a release: This [Alumet](https://github.com/alumet-dev/alumet/releases/tag/v0.6.0)

**To Reproduce**
1. Run alumet local agent or client: **./app-agent**, no arguments are needed
2. Wait alumet for retrieving some values
4. Look in output

**Expected behavior**
The output should not contains lines if their uid is a CRIO part.

**Logs / Output**
Logs are not relevant here,  but here is the csv output example:
![image](https://github.com/user-attachments/assets/33a43c32-be59-4ac7-b5ae-e976c8dbed98)
As we can see, these lines have their columns *uid* containing CRIO layers

**Comment by TheElectronWill** [comment]
Can you please include an example of the unnecessary data? What do you mean by "crio layers"?
