### ISSUE TITLE
Build documentation is outdated after v0.6

### ISSUE THREAD

**Issue by laurent-morin** [alumet-dev/alumet#53]
I have tried to build the app-agent on different OS. Each time with different rust version and I add different error message: 
I have tested : 
- Ubuntu 22.04.4 LTS
- Debian 12
- Red Hat 8.7

And within the latest rust docker image, i have nothing more than some lib files in the target/debug directory.

What is the environment of current developement ?

PS: I have used the main branch

**Comment by TheElectronWill** [comment]
Hello!

We've built the agent for several environments, including Ubuntu 22.04.4 (which I use daily).

Which flags did you use?
What error messages did you get? (I don't see it in the issue)

**Comment by Leer0r** [comment]
I agree with @laurent-morin 
I try myself to build the local agent with the [user book](https://alumet-dev.github.io/user-book/installation/install.html)

It mention to use `cargo build` inside the `app-agent` folder. But it seems that only libraries are builds, not the binary
With the command given in the `app-agent` README (`cargo run --bin alumet-local-agent --features local_x86`), it produce the `alumet-local-agent` binary

It can be helpful to have theses instruction directly in the user book

**Comment by TheElectronWill** [comment]
You're right, the user book does not properly reflect the latest version that is on the main branch. I'll update it :)

**Comment by TheElectronWill** [comment]
Resolved by https://github.com/alumet-dev/user-book/pull/7
