### ISSUE TITLE
Finalize the first version of the Kubernetes plugin

### ISSUE THREAD

**Issue by TheElectronWill** [alumet-dev/alumet#9]
See #5

**Comment by TheElectronWill** [comment]
Yes!

Next time you can write "resolves #N" or "closes #N" (replace N by the issue number) in the description of the Pull Request. When the PR is merged, issue N will be closed automatically :)

**Comment by titouanj** [comment]
Oh Guillaume is too fast for me

**Comment by titouanj** [comment]
Fixed by #17

**Comment by TheElectronWill** [comment]
> Oh @TheElectronWill is too fast for me

It's the fire of Alumet! 🔥
